project:
  type: website
  output-dir: docs

website:
  title: "The Plots Thicken"
  favicon: favicon.ico
  navbar:
    background: "#0a0a0f"
    foreground: "#ffffff"
    logo: ""
    left:
      - text: "Home"
        href: index.qmd
      - text: "Plots"
        href: plots/index.qmd
      - text: "About"
        href: about.qmd
      - text: "Contact"
        href: contact.qmd
  page-footer:
    background: "#0a0a0f"
    center: "© 2025 The Plots Thicken"

format:
  html:
    theme: [flatly, custom.scss]
    css: styles.css
    toc: false
    page-layout: full
    lightbox: true
